version: '3.8'

services:
  ha-bridge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HA_URL=${HA_URL:-http://homeassistant.local:8123}
      - HA_TOKEN=${HA_TOKEN}
      - API_KEYS=${API_KEYS:-["default-key"]}
      - CACHE_TTL=${CACHE_TTL:-300}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED:-true}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring